resolver: lts-8.12

packages:
  - location: .
  - location:
      git: https://github.com/hedgehogqa/haskell-hedgehog
      commit: 675780808c2e094cd4906a1d68c1c4203b2cfe15
    extra-dep: true
    subdirs:
      - hedgehog

extra-deps: []

flags: {}

extra-package-dbs: []
