resolver: lts-8.13

packages:
  - location: .
  - location: '../haskell-hedgehog'
    extra-dep: true
    subdirs:
      - hedgehog
  - location: '../ghc-typelits-natnormalise'

extra-deps: []

flags: {}

extra-package-dbs: []
